name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bash Automated Testing System
      uses: mig4/setup-bats@master
      with:
        bats-version: 1.2.0
    - name: Run Tests
      run: bats test
